"""Agregar stock a productos y crear entradas

Revision ID: 39029e49983d
Revises: 900331194680
Create Date: 2025-08-25 20:35:00.484124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39029e49983d'
down_revision = '900331194680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrada_detalle', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_entrada'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_producto'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'productos', ['id_producto'], ['id'])
        batch_op.create_foreign_key(None, 'entrada_almacen', ['id_entrada'], ['id_entrada'])

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('stock',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('entrada_detalle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_producto'), 'productos', ['id_producto'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_entrada'), 'entrada_almacen', ['id_entrada'], ['id_entrada'], ondelete='CASCADE')

    # ### end Alembic commands ###
