"""Add unidad_medida to productos

Revision ID: ed675a324ff1
Revises: 39029e49983d
Create Date: 2025-08-26 21:13:45.321622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed675a324ff1'
down_revision = '39029e49983d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidad_medida', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('unidad_medida')

    # ### end Alembic commands ###
